### PR TITLE
Feat : Add Weekly report button in views.php

### PR DESCRIPTION
**Pull request by alexbelgium**
The report already exists and is accessible from the settings options, why not show it from the front page? Especially useful when publishing the site to people who won't have access to the authentified functions

Or was it not included on purpose as it might seem rather empty in its current state ?

### CODE REVIEW

**Comment by alexbelgium** [comment]
We might imagine having a weekly chart also by modifying the daily_chart.py to a weekly_chart.py with the inclusion of all data between two sundays... I'll add this to the PR

**Comment by lloydbayley** [comment]
Well this is quite nifty! I like it! Seems to work well. It's a good idea to find the latest detections and make sure they are legitimate! I found one which was a result of children making noise (damn kids interfering with my soundscapes!)

**Comment by alexbelgium** [comment]
Well this button is already accessible through the options ; but I was thinking we could make it more visible

For problematic detections such as you describe I use telegram notifications that alerts me when an unexpectely exotic bird appears in the garden (usually ends up to be my neighbor calling for her cat in a repetitive monosyllabic manner)

Also ; I was wondering if it would be worth it to create a weekly chart in addition to the daily one to complement the descriptive statistics ; but well I guess I have created you and Nachtzuster enough work already to double check & troubleshoot the code ;-)

**Comment by Emmo213** [comment]
I like this idea. If I was going to nitpick I'd put the weekly report button after the daily chart button just because I think it makes more sense to have the two date based buttons next to each other.

**Comment by alexbelgium** [comment]
I would have wanted also a weekly chart, it should look good and avoid the "empty look" of this page but I don't know enough to code it

**Comment by Emmo213** [comment]
Thank you, sir.

**Pull request merged**
