### PR TITLE
Backup download & Backup Restore

### PR DESCRIPTION
**Pull request by Nachtzuster**

### CODE REVIEW

**Comment by Nachtzuster** [comment]
Thanks for the review!

The script doesn't need to figure out fpm anymore, fortunately. I must have overlooked that line while merging - oops.
Regardless, yes, the user should get some error if the script fails somehow, I'll have a look into that.

> Would it be possible to only download the tar if scripts exists as "exit 0" and otherwise print the error output ?

No: since the tar is created on the fly and piped to php, the script will exit with 0 only after the whole thing was already downloaded by the user (well, in the happy case at least)

**Comment by alexbelgium** [comment]
> I'd like to change the upload to a 'streaming' solution like the download already is to avoid having to write the tar to sd card and having to have double space requirements. Not sure if I'll figure that one out though.

Nice idea indeed I didn't knew that was possible.

**Comment by Nachtzuster** [comment]
Turns out Raspberry Pi OS doesn't have tmpfs mounted on /tmp. So during restore every uploaded chunk _still_ ends up on the SD card before it is un-tar-ed :disappointed: 
That is a problem to be solved some other day.

**Comment by alexbelgium** [comment]
Nice!

**Pull request merged**
