### PR TITLE
Readme : Homeassistant addon as installation solution

### PR DESCRIPTION
**Pull request by alexbelgium**

### CODE REVIEW

**Comment by alexbelgium** [comment]
Dockerisation of your instance of BirdNET-pi using https://github.com/gdraheim/docker-systemctl-replacement to convert it to a working addon

**Comment by lloydbayley** [comment]
A nice idea in theory but it's not using this fork as the installation candidate, so I'm a bit confused as to why.

**Comment by alexbelgium** [comment]
> A nice idea in theory but it's not using this fork as the installation candidate, so I'm a bit confused as to why.

Actually, it is using this fork :
https://github.com/alexbelgium/hassio-addons/blob/c4c02a756a476ec8d63b1d5e2271014268971dba/birdnet-pi/Dockerfile#L55-L57

**Comment by lloydbayley** [comment]
I stand corrected. My apologies. I was basing that on the HACS listing from a week ago. I see things have changed.

**Comment by alexbelgium** [comment]
No worries! I've indeed made an addon on the birdnet-go version which was easier to start with as already had a docker image ; but moved on to birdnet-pi as I realized how it is incredibly complete and well designed... and more importantly still being developed through this fork :-)

The hard work being to set the initial addon which is now done, I'll be supporting both in parallel

**Comment by lloydbayley** [comment]
Understood, I was a bit affronted when I saw a BirdNet-Pi install which pointed to and said it was developed by another user. Even though the original repo is no-longer maintained, the credit should be with the author. I now see that the the list has been updated to BirdNet-Go and not Birdnet-Pi. Again, my apologies for the quick reaction.

**Comment by alexbelgium** [comment]
Documentation is not my forte btw ; I'll update the Readme's to make more apparent the rightful credits. And beautiful saying indeed ! ;-)

**Comment by lloydbayley** [comment]
You're doing well!

**Comment by Nachtzuster** [comment]
Neat.

Maybe remove the 'To do this :' section and just link to the readme in your repo instead?

**Pull request merged**
