### PR TITLE
Adminer iframe ?

### PR DESCRIPTION
**Pull request by alexbelgium**
Hi,

Everything uses iframe in BirdNET-Pi, is there a specific reason why adminer would not ?
I just changed the X-Frame-Options from Deny to Sameorigin and it seemed to work on my system?

It seems the downside is that we lose location when refreshing the page ; but database modification should not occur frequently so it should not be such an issue. For these specific cases, I've added a link to open adminer in a new page if needed

### CODE REVIEW

**Comment by alexbelgium** [comment]
Btw it seems the file encoding was not UTF8 and it was converted automatically when updating from github online, not sure it is an issue or not

**Comment by Nachtzuster** [comment]
> Everything uses iframe in BirdNET-Pi, is there a specific reason why adminer would not ?

I have no idea :smile: 
Most likely it was just the path of least resistance

I'm fine with having it in an iframe, makes everything consistent. :+1: 

I would like the files keep the original encoding to keep the diffs sane, could you fix that?

**Comment by alexbelgium** [comment]
Sure - i don't know yet how but will do it ;)

**Comment by alexbelgium** [comment]
Should be good! Thanks

**Pull request merged**
