### PR TITLE
UI : Convert checkbox to toggleswitch

### PR DESCRIPTION
**Pull request by alexbelgium**
Not very useful but prettier :-)
Tested on windows and ios

Before : 
image

After :
image image
image image

### CODE REVIEW

**Comment by bdeschut** [comment]
Personal opinion: for me it wouldn't be clear if the toggle is on or off, given that the color or the text doesn't change (I refer to the two screenshots you provided). Perhaps add some color?
image

**Comment by alexbelgium** [comment]
Thanks for the feedback, indeed makes total sense ! As I haven't modified the main css files to make it simpler, it would need to cover both light and dark themes. Would such a layout be ok : 

image
image

**Comment by bdeschut** [comment]
It is definitely an improvement. Not sure if difficult, but for the dark theme (and the light theme as well), this might also be an option:
image

**Comment by alexbelgium** [comment]
Thanks for the suggestions. I'm not a fan of text on small elements like that - it would in my opinion lead to clutter especially on smaller screens. However I do understand that the difference of light vs grey shades could be not super explicit. 

Here is an update : 
- transparent background when inactive (good for all themes)
- complex dark gray when active (good for all themes) plus small ON

image
image
image
image

**Comment by alexbelgium** [comment]
What is preferrable : "check" or "ON"

**Comment by bdeschut** [comment]
Both are clear for me, I slightly prefer the check sign

**Comment by alexbelgium** [comment]
Thanks for your feedbacks and proposals

**Comment by Nachtzuster** [comment]
> Not very useful but prettier :-) Tested on windows and ios
> 

quite :smile:

**Pull request merged**
