### PR TITLE
Feat : Confirmed species

### PR DESCRIPTION
**Pull request by alexbelgium**
The idea of this PR was that I wanted to verify which species are really there (= seen visually, or that I am 100% sure to be true) and which species are just probable. I've therefore implemented a simple text file to list confirmed species. If the species is not confirmed, there is a "?", if it is confirmed, there is a "checkmark".

Description : this feature proposal is to be able to visually show which species were verified to be confirmed, and which are not

How : 
- proposal is to create a new txt file named confirmed_species_list.txt that would contain the name of the confirmed species
- when the Common Name is loaded in all page, it checks if it is part of this file. If yes, a little check icon appears next to it

Alternative considered : 
- Confirming observations at the level of the detection with a storage of the status in the sqlite - this would be too cumbersome and increase needlessly the sqlite size

It is possible to shift from one to the other by just clicking on the icon

image
image

### CODE REVIEW

**Comment by wenestvedt** [comment]
I like this idea!

Will there also be a way to mark species through the web interface?

**Comment by alexbelgium** [comment]
> I like this idea!
> 
> Will there also be a way to mark species through the web interface?

Yes! By clicking on the icon it alternates between confirmed (check) and to confirm (question mark)

**Comment by alexbelgium** [comment]
I haven't added an update snippets as the file gets created on first access

**Comment by Emmo213** [comment]
While a neat idea if somebody didn't want to verify all their species there'd be a lot of question marks that wouldn't be helpful to them and would take up screen real estate. What about making it available as an on/off option through the settings?

**Comment by Emmo213** [comment]
It was just a suggestion. Maybe see what @Nachtzuster thinks? But you're right, being on the recordings page wouldn't be too intrusive.

**Comment by alexbelgium** [comment]
Ok I've added the option to enable/disable

**Comment by lloydbayley** [comment]
I'm with you Alex, we need to start a bit more actively considering what's absolutely necessary/productive in BirdNet as you say to avoid cluttering as you know what the old code looked/looks like! It's what I was always saying that we have to say no sometimes to the little extra what-I-call 'lipstick and eyeshadow' things that people fancy but stand the change of over-complicating things when it comes to debugging what they break. We've seen how this went in times gone by...

**Comment by alexbelgium** [comment]
No problem to me not to implement this, I've already added it anyway in my add-on. A plug-in system would be the best for modular options but alas the current coding logic in php does not easily supports this and this would be too big a work to implement that

**Comment by lloydbayley** [comment]
Nono, I didn't mean not to put this one in, I was just thinking about how best to proceed. The plugin idea is quite interesting, I'll give it some thought!

**Comment by alexbelgium** [comment]
I wonder if by placing a `\\plugin` placeholder in some critical places we could actually implement this by inserting code in those places at installation... Globally the update_snippets could be used to install plug-ins and insert the code in the needed places... Mmh if we found a robust way to implement that it would be an optimal solution between cluttering and very user specific functions (I remember the guy who wanted to implement dynamic GPS to allow for a travelling birdnet-pi for example)...

**Comment by lloydbayley** [comment]
Robust is the key here. You're absolutely and the placeholder would be a harmless idea for the future. Easily-removed if abandoned or changed. Nice one. I've just banged off an email to you and now I must go to bed! Its: 2:35am AGAIN! I can't help myself!

**Comment by alexbelgium** [comment]
Ideas for further usage : 
- Have a +10% detection threshold for unconfirmed species
- Only export to birdweather confirmed species
- Only inform on apprise for unconfirmed species occurrence

**Comment by lloydbayley** [comment]
Wow! I've never seen a lint fail for over-indenting before! That's a new one for me!

**Comment by alexbelgium** [comment]
> Wow! I've never seen a lint fail for over-indenting before! That's a new one for me!

Strangest thing also is that I didn't touch it, it is the same initial code!

**Comment by alexbelgium** [comment]
I've implemented a differential detection level for confirmed species but might remove it ; still hesitating on the usefulness. It's all a matter of quality vs quantity...

**Comment by alexbelgium** [comment]
Mmh not convinced with the specific detection level for confirmed species. I'll probably remove it

**Comment by alexbelgium** [comment]
Closed, but I'll continue to update it as it is merged on the fly in my homeassistant add-on

**Comment by alexbelgium** [comment]
Added a feature to select only confirmed or unconfirmed species :

image

**Pull request closed without merging**
