### PR TITLE
Feat : sort species by max confidence

### PR DESCRIPTION
**Pull request by alexbelgium**
Hi,

Still trying to sort through all my species, and I wanted to try to sort by max confidence. In the end this can be even more useful than sorting by count for atypical species as was demonstrated when I had a single traveling bird that came (so 3-4 occurences) but with a 99% detection value. On the other hand, I have an abnormal specie with tons of detections but none above 95% which could indicate a false positive. 

Here is the code - I was wondering if this could be useful to the more global community.

Also, I made a specific button to reflect the "sort by confidence" as currently the page for individual observations of a species use the "sort by occurences" icons instead.

image

### CODE REVIEW

**Comment by Emmo213** [comment]
Oo, I like this idea.

**Comment by lloydbayley** [comment]
Works for me. We like this one. Very handy. +1 for commit!

**Comment by Emmo213** [comment]
Really good enhancement. I added it to my Best Recordings page too.

**Comment by alexbelgium** [comment]
Thanks! Could you please provide the PR? Indeed we might as well make it there too!

**Comment by Emmo213** [comment]
If you'd like it here's my commit. 

https://github.com/Emmo213/BirdNET-Pi/commit/671a47dde3c6741d8379289c342a19297801fb4f

**Comment by alexbelgium** [comment]
Thanks! I'll already merge it in my fork (used for the HA addon) but indeed it would be good to have it in the main app. I'm not at my computer for the moment but will test asap

**Comment by alexbelgium** [comment]
@Emmo213 : thanks the PR is created !

**Pull request merged**
