### PR TITLE
Changed the imagelink from people to photos

### PR DESCRIPTION
**Pull request by Emmo213**

### CODE REVIEW

**Comment by alexbelgium** [comment]
Hi, the new link for photos works great, thanks!

Not sure about the clear cache button, what should it do ? If I click on it and go on the main page (overview) it still shows the same picture for the bird ? Thanks!

**Comment by eDad2003** [comment]
Thanks for working this URL bug & doing some code cleanup in the process - variable names matter!  I'm still working on getting set up and being comfortable to contribute in the future.

**Comment by Emmo213** [comment]
> Hi, the new link for photos works great, thanks!
> 
> Not sure about the clear cache button, what should it do ? If I click on it and go on the main page (overview) it still shows the same picture for the bird ? Thanks!

Birdnet will only fetch the image from Flickr if the image isn't already in the cache, which is stored in PHP SESSION variable. So even after my fix if you clicked on an image and the the image was already in the cache the link to the image had "people" in it but once the cache is cleared it'll refetch the image and now correctly show "photo" in the link. Clearing the cache doesn't necessarily change the image that's being shown.

**Comment by Nachtzuster** [comment]
@Emmo213 thanks for providing a PR so fast.

I'm going to push a somewhat simpler fix though, sorry.

Also I won't be including the cache reset, that will take care of itself when the session expires after a day or so.
Should people be so annoyed by the faulty url, they can always delete the cookie in their browser to force a new session.

**Comment by Emmo213** [comment]
It's your repo but can I ask what's wrong with the code? It fixes the bug and provides additional functionality if people want to use it. Otherwise you'll have comments like the guy who opened the bug saying just changing from 'people' to 'photos' only works sometimes.

**Comment by Nachtzuster** [comment]
@Emmo213 as I said it could be simpler. I like simple. :shrug: No offence meant.
for reference: https://github.com/Nachtzuster/BirdNET-Pi/commit/25f2c531c0379125ede04991035830461f42f4bc

**Comment by Emmo213** [comment]
None taken. I'd just like to be able to contribute in the future and didn't know what your guidelines were. 

I'll close my PR. Thanks.

**Comment by alexbelgium** [comment]
> None taken. I'd just like to be able to contribute in the future and didn't know what your guidelines were.
> 
> I'll close my PR. Thanks.

Hi, it is also my first time contributing (that much) to a project that I do not own fully. Here is my personal recommendation on how to integrate in an existing project and be able to provide the contributions that we want. One key element in my opinion is that many developers don't have that much time to give to those free projects in parallel to their already full life, so they (myself included) look to things like : 
1. is it useful to a majority of people (= avoiding too much niche settings to keep things simple)
2. is it easy to review & integrate (by doing incremental updates using the same coding logic, variables, functions as the existing code)
3. is there a risk of breaking things (for example PR on a single file or tweaking an existing function are much safer than an update spanning 5 files adding new functions)

It is also tempting to want to improve underlying logic, however even if the current logic is not the best, it makes it MUCH easier to remember how things work and to manage the code at longer term when everything is consistent. Changing the underlying logic of how things work would more be part of a larger rewrite, which would be a daunting task (in terms of coding, testing...) that would not be consistent with a hobby support project.

As such, I think the best thing to do when doing PR is look at how the code & logic is structured, and align with this methodology. Review & testing is therefore much facilitated, and your PR is much more likely to be integrated to this great project for everyone's benefit !

**Pull request closed without merging**
