### PR TITLE
Proposal to move success message to js alert

### PR DESCRIPTION
**Pull request by alexbelgium**
https://github.com/Nachtzuster/BirdNET-Pi/issues/92

### CODE REVIEW

**Comment by Nachtzuster** [comment]
This would be much better indeed, thanks.

The advanced settings page could use the same improvement: could you add it there too?

**Comment by alexbelgium** [comment]
Sure, done!

**Comment by Nachtzuster** [comment]
weird: on the advanced settings page, the `Settings successfully updated` popup does not show.

the `Settings` and `Advanced Setting` page apparently work differently enough that the same tweak does not do it

**Comment by alexbelgium** [comment]
Sorry I did not test it just copied blindly ;-) I'll do some test

**Comment by alexbelgium** [comment]
My fault, I'll correct the error

**Pull request merged**
