### PR TITLE
Feat : proposal to standardize behavior of click on Com_Name and Sci_Name

### PR DESCRIPTION
**Pull request by alexbelgium**
This PR harmonizes the behavior of what happens when clicking com_name or sci_name on different pages, and makes more explicit the external links by using icons : 
- Click on com_name = open species page
- Click on sci_name is disabled
- There is 4 icons now : 
    - If not in kiosk mode : (i) open info_site ; (w) open wikipedia
    - For both mode : open minigraph, open spectrogram page
- The link to open spectrogram appears both for mobile and desktop, I don't see why it was mobile only before

Requires : [#113](https://github.com/Nachtzuster/BirdNET-Pi/pull/113)

Before/after : 
- Last species detected
image image image
- 5 latest overview
image image
- Todays's species : 
image image
- Recordings : 
image image
- Stats : 
image image

### CODE REVIEW

**Comment by alexbelgium** [comment]
Clarified the pictures. Main remaning element : should minigraph be added to the Recordings as well

**Comment by Nachtzuster** [comment]
nice!

**Comment by Nachtzuster** [comment]
> Clarified the pictures. Main remaning element : should minigraph be added to the Recordings as well

Probably not: in my mind, recordings is more a historic data browser, while the other pages are more a 'what's going on' thing

**Comment by alexbelgium** [comment]
Thanks, added. Agree with the minigraphs - and it would request a code refactor probably (move minigraphs to common.php) to make it more transversal, so let's keep as it is ;-)

**Comment by Nachtzuster** [comment]
@alexbelgium I guess this one is ready for merging too, right?
Just one question: where are the icons coming from? ie. are 'we' allowed to use them?

**Comment by alexbelgium** [comment]
;-) Hi, ready for merge indeed I've been using it for the past week and did not find issues that I have not corrected yet

Regarding icons : the wikipedia one comes from their website under CC (https://be.m.wikimedia.org/wiki/File:Tango_style_Wikipedia_Icon.svg) ; and the information one from wikipedia without any constraints (https://commons.wikimedia.org/wiki/File:Information-icon.svg)

Btw I took those as they were convenient and easily readable but we could adapt their style if you preferred (all rounds or all squarish)

**Comment by Nachtzuster** [comment]
Thanks @alexbelgium

**Pull request merged**
