### PR TITLE
Feat : change specie detected

### PR DESCRIPTION
**Pull request by alexbelgium**
Objective : provide a way to change a misidentified detection

Status :
- [x] script creation to change database and move files
- [x] initial working function to call script by passing both the filename, and the new expected specie
- [x] nice overlay for the dropdown list that works on every page

Implementation :
- User interface: new button that calls a change detection specie
image
- Click opens a dropdown list as an overlay with a user input box to filter
image
- Then asks confirmation
image

How : 
- The function calls a shell script that changes both the database (scientific name, common name, filename) and moves the files if existing to the correct place
- Use of modal box for overlay

### CODE REVIEW

**Comment by alexbelgium** [comment]
Ok seems to work both on web and mobile

**Comment by alexbelgium** [comment]
I've corrected the curl paths above, they were not correct

**Comment by alexbelgium** [comment]
@lloydbayley : did you install the PR with the code I was showing above using curl ?

If we break down by elements : 
# Working in your test : 
- image appears
- function is called
- modal css is displayed
- PR with similar filtering function is working : https://github.com/Nachtzuster/BirdNET-Pi/pull/69
# Not working in your test : 
- [ ] Empty selection box
- [ ] Cancel modal box by Esc or click in blank

I'll push some potential fixes that could make it work on my system and not yours

**Comment by alexbelgium** [comment]
I think the path for labels was specific for my addon, please let me know if this now works! cheers

**Comment by lloydbayley** [comment]
Sorry, was overtaken by events. Will try it now!

**Comment by lloydbayley** [comment]
Well, the first part works but (YIPEE) but when I click to change it, I get:

image

In a browser popup.

**Comment by alexbelgium** [comment]
thanks ; that's due to php being executed by user caddy and on my addon i gave "caddy" and "pi" the same accesses 1000:1000 to avoid such issues :-) I'll see how to adapt and execute using a sudo -u pi command

**Comment by lloydbayley** [comment]
Just remember that the user may not necessarily be 'pi'. I like the bend the rules on Dev machines and have a few things non-standard to see what happens when it goes outside the box! :)

**Comment by alexbelgium** [comment]
Should be good! Now user pi will execute the script, which also allows to make sure that the script has only access to "pi" files

**Comment by alexbelgium** [comment]
Thanks so much for these tests - this allows that way to test on both : 
- Servers : rpi4 aarch64 addon (mine) and x86 VM BirdNET-Pi (yours)
- Interface : windows ; mac ; ios

Which should cover most of the users systems ;-)

**Comment by lloydbayley** [comment]
Getting there. Small typo that yields:
```Error : sudo: /home/pi/BirdNET-Pi/scripts/birdnet_changeidentification.sh: command not found<br>```
You've left a _ out of change_identification!

**Comment by alexbelgium** [comment]
argh I'll correct ; thanks

**Comment by alexbelgium** [comment]
Actually the path was correct ; perhaps it was because there was no exec command. I'll add it. Or missing permission on the sh file for user pi ?

**Comment by lloydbayley** [comment]
Sorry:

```Error : sudo: exec: command not found<br>```

**Comment by alexbelgium** [comment]
I see - the issue is actually due to $home not being defined I'll correct that (now why was it working on my system...)

**Comment by lloydbayley** [comment]
Lots of fun, this debugging thing isn't it? Ha

**Comment by lloydbayley** [comment]
Sorry Alex, same:

```Error : sudo: exec: command not found<br>```

**Comment by alexbelgium** [comment]
mmh don't you have bash installed? Perhaps I should use sh and that the issue from the start was the shebang of the script

**Comment by lloydbayley** [comment]
I certainly do have bash installed. Just a normal bash shell.
Also noticed you have hardcoded /home/pi at the top of the script (not that it makes any difference to the current problem)...Just pointing it out.

**Comment by alexbelgium** [comment]
Just for good measure as I see you don't use the use "pi" as main user I've ensured the script does the same ;-) it avoids the next error you would have encountered :-)

**Comment by alexbelgium** [comment]
thanks, HOME is corrected to ${HOME:-/home/pi} ; that should cover all user usages

**Comment by lloydbayley** [comment]
Gimme a sec...you're pushing them faster than I can revert and re-pull! :)

**Comment by lloydbayley** [comment]
Same again, I'm afraid...Although, it did think about it for a fraction of a second longer.
Also, just looking (I know the shebang takes care of it but the permissions of all the other .sh are 777 (although, I tried that manually and it still shouted at me!)

**Comment by alexbelgium** [comment]
mmh... I don't understand why it doesn't work on your system and it does on mine. especially as I'm using the same logic (calling $user and $home) as being used in other scripts... and the worst is that initially it worked !

So the issue came when when we started calling the "sudo -u $user" to access the script it seems...

**Comment by lloydbayley** [comment]
I'm just debugging the php call to the script on my end. I think that's where it's going wrong...

**Comment by lloydbayley** [comment]
Whilst I'm checking, have you done anything strange with visudo or sudoers in your environment that wouldn't be in a normal install? I'm just debugging what is being sent to bash from php on my end.

**Comment by alexbelgium** [comment]
I did add everyone to sudoers `echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers `
https://github.com/alexbelgium/hassio-addons/blob/03e9ad44329c826b8144fac0943659610b32e1e1/birdnet-pi/Dockerfile#L54

But at the same time other scripts are also called using the same log such as : `shell_exec("sudo -u".$user." git -C ".$home."/BirdNET-Pi fetch > /dev/null 2>/dev/null &");`
https://github.com/Nachtzuster/BirdNET-Pi/blob/e0e5aff08175c9d0678ee8d8755da04d7c996a70/homepage/views.php#L16C3-L16C94

**Comment by lloydbayley** [comment]
HANG ON......Why is the word exec being put to the bash shell?
```("sudo -u ".$user." exec ".$home."/BirdNET-Pi/scripts/birdnet_changeidentification.sh \"$oldname\" \"$newname\" log_errors 2>&1");```
That shouldn't be there, surely...that's why it's trying to execute exec. Let me take it out and try

**Comment by alexbelgium** [comment]
it initially wasn't there and I added it due to the "command not found". I've pushed to check by removing the exec and aligning the "sudo -u" code with how it is called in other php files in birdnet-pi

**Comment by lloydbayley** [comment]
Well bugger. You're too quick off the mark. Will retest with latest commit.

**Comment by alexbelgium** [comment]
> BINGO. That was it. `("sudo -u ".$user." exec ".$home."/BirdNET-Pi/scripts/birdnet_changeidentification.sh \"$oldname\" \"$newname\" log_errors 2>&1");` Should read: `("sudo -u ".$user." ".$home."/BirdNET-Pi/scripts/birdnet_changeidentification.sh \"$oldname\" \"$newname\" log_errors 2>&1");`

Perfect!!!!! thanks very much I'll align final code with this line

**Comment by alexbelgium** [comment]
Well actually I've aligned the code with your proposal... so it should work in theory ? at least the code is aligned with your proposal in https://github.com/Nachtzuster/BirdNET-Pi/pull/62#issuecomment-2122702645

**Comment by lloydbayley** [comment]
Ok...So I test now? :)

**Comment by alexbelgium** [comment]
yes please :-)

the only difference I see from your working code is that you have : 
`("sudo -u ".$user." ".$home."/BirdNET-Pi/scripts/birdnet_changeidentification.sh \"$oldname\" \"$newname\" log_errors 2>&1");`
while my current code is
`("sudo -u ".$user." ".$home."/BirdNET-Pi/scripts/birdnet_changeidentification.sh \"$oldname\" \"$newname\" log_errors 2>&1", $output))`
should the ";" be there? I don't see it's function in this code?

**Comment by lloydbayley** [comment]
It's ok. Was leftover from when I was debugging in a php -a session locally and I didn't test for $output because it wasn't important in that test, so yet, that's correct. Will try it now.

**Comment by lloydbayley** [comment]
Ok. We're 99% there. It failed because the sh file is still not 777. Did that manually and re-tested and it works perfectly.

**Comment by lloydbayley** [comment]
God....I've pushed him too hard and killed him!

**Comment by alexbelgium** [comment]
That's so great thanks very much!!! So the current code in play.php works??

**Comment by lloydbayley** [comment]
Yep. Just need to fix the file permissions!

**Comment by alexbelgium** [comment]
I don't see specific chmodding if the scripts in the main code ; I think it is managed through `chmod -R g+rw $my_dir` in  https://github.com/Nachtzuster/BirdNET-Pi/blob/a22c7c089fa94eb56df04d2b5812d28ef379bba4/scripts/install_services.sh#L85

So if the PR is pushed the permission should be set hopefully in the same way as the other scripts

**Comment by lloydbayley** [comment]
Well, it is created with 644 and when I changed it to 777, it started working. That's all I know!

**Comment by alexbelgium** [comment]
Thanks I wonder then why the other scripts are at 777...  Well anyway i'll see how to plug-in this :) 

Thanks very much for your availability and the very dynamic troubleshooting!!

**Comment by alexbelgium** [comment]
Sure ! I'm have to go but will check that Tomorrow ;)

**Comment by lloydbayley** [comment]
Fair enough! I should go to bed here! Have a evening.

**Comment by alexbelgium** [comment]
## Permissions
I've checked - so once the PR will be merged ; people will have to update their installation by executing "newinstaller.sh" according to https://github.com/Nachtzuster/BirdNET-Pi?tab=readme-ov-file#installation to allow update.

This script will execute install_services.sh that will give permissions according to chmod -R g+rw $my_dir

I guess this would take care of the permissions required to execute the scripts... as it would for the other ones. I'll ask Nachtzuster once the ok message is done

## Ok message
I'll add this today

**Comment by lloydbayley** [comment]
How do you mean people will have to update their installation with newinstaller.sh? When the internal update happens, it will call birdnet_update and the snippets updater. I'm not with you I'm afraid. Have I misunderstood>?

**Comment by alexbelgium** [comment]
Hi, sorry i have never used the app updater and thought from this phrase in the readme that the newinstaller.sh script was the recommended way to update : `The installer takes care of any and all necessary updates, so you can run that as the very first command upon the first boot, if you'd like.`

I looked at the updater code and this line `find $HOME/Bird* -type f ! -perm -g+wr -exec chmod g+wr {} + 2>/dev/null` should give the same permissions to the newly added files

Sorry for the confusion - just meant it doesn't seem that a specific permission for this new script should be set

**Comment by lloydbayley** [comment]
Nono, it's fine. It's just that people won't run that or know to run it. They will use (hopefully) the internal update button etc etc. I think you're on the right track now. @Nachtzuster care to comment?

**Comment by lloydbayley** [comment]
Ahh god, there's no rush. I like the icon too. Very suitable! :)

**Comment by alexbelgium** [comment]
Full disclaimer : it is not mine but from https://www.pngegg.com/en/png-xvmvs under "Non-commercial use, DMCA" which should allow its usage :)

**Comment by alexbelgium** [comment]
> Question: should the file be marked somehow as being changed manually? eg by setting the confidence to a impossible number like `00`

Should we set `0` as confidence level, or `0.00$previous_confidence_without_dots` to avoid losing the initial info ? That would result in a confidence of `0.0009078` for example for an initial value of 0.9078 (as it seems detection can have 3 or 4 significant digits). In the main main script, I've tried it and it simply appears as a rounded value of `0%`

Please tell me your preference, both are very easy to implement

**Comment by Nachtzuster** [comment]
@alexbelgium sorry for the late response - long, offline weekend

I like keeping the information, but since we have to loose the original species anyway, it does not make much sense to keep the confidence number, I think

**Comment by alexbelgium** [comment]
This makes sense indeed ; the confidence value looses all meaning. Ok i'll implement the 0!

No worry about late responses I really appreciate the time you take for this work and to review my code also!

And I've been quite busy testing several different audio recording systems to find the best one :)

**Comment by alexbelgium** [comment]
Actually shouldn't confidence be 1.01 as done manually? The value above 1 would still show it is a "modified" value but it would avoid messing stats or colors in the graph about quality of detection? Just floating the idea as i'm not 100% sure myself yet of the value to set ;)

**Comment by Nachtzuster** [comment]
> Actually shouldn't confidence be 1.01 as done manually?

Makes sense - humans always know better! :-)

**Comment by alexbelgium** [comment]
Just thought of an issue : if we set confidence at 1 it means that modified files will always be the ones showed in the "best recordings" while they likely are not. So perhaps we should indeed keep 0...

**Pull request merged**
