### PR TITLE
Updated daily chart to use the theme selector

### PR DESCRIPTION
**Pull request by Emmo213**
This will allow the daily chart to be green or grey based on the theme light or dark, respectfully. 

Edit: I should note this is the first time I'm contributing to another project like this so if I goofed on something procedurally please let me know.

### CODE REVIEW

**Comment by Emmo213** [comment]
One thing I'm still tweaking is based on the way the daily chart image gets generated when the theme is changed it doesn't always immediately update the plot but you have to refresh the page once for the change to take place. I don't expect people to change themes frequently so I don't think it's a big deal but if I can get it to update better that'd be preferable.

**Comment by alexbelgium** [comment]
Nice! Haven't tested it yet but thanks for the PR. Indeed I guess people are either team "light" or team "dark" and don't really switch often

**Comment by alexbelgium** [comment]
Hi, really nice to have colors on the graphs! Thanks!

I see what you are proposing to move the settings to a "settings table" in the birds.db but this might be a big change in logic vs the current code... Although it is not perfect, it is probably better to use the current logic of storing variables in birdnet.conf. Indeed I see that the downside is that depending on the theme selected, some graphs might have different colors but I think that's not so much an issue as people would anyway likely keep a theme stable after having tested a few... and that modifying a core element (how settings are stored) would need to be seen in a larger way to keep homogeneity in the whole code ! 

I think it can still keep the core function of your proposal : based on the theme, define the colors of the graph and store it as a png in the folder. what do you think ?

**Comment by Emmo213** [comment]
While I thought about moving all settings to the database that wasn't part of my proposal, but this does allow for new settings to be added to the database in the future. The only setting in there right now is the theme one. If you can read/write to the existing settings file easily that's fine but I do think the database is a better long term solution. Since the original BirdNET-Pi is no longer maintained we don't have to keep all the legacy code if we don't want to.

**Comment by Nachtzuster** [comment]
> Edit: I should note this is the first time I'm contributing to another project like this so if I goofed on something procedurally please let me know.

One would probably be: one feature at a time. :wink: 
Please re-use utils.helpers.get_settings

@alexbelgium would this complete the whole dark theme?

About that other feature: Unix-y programs that don't use a plain settings file under /etc are few and far between, there's reasons for that.

**Comment by alexbelgium** [comment]
> @alexbelgium would this complete the whole dark theme?

Hi, indeed having the graph colors aligned with the theme would be a positive element! Actually last element to finalize the dark theme now that the third party parts (phpsysinfo ; ...) are also dark.

**Pull request closed without merging**
