### PR TITLE
Test notification using same code base

### PR DESCRIPTION
**Pull request by Emmo213**
As mentioned in another pull request #167 the test notifications and regular notifications should use the same code base. These changes create a fake bird detection to allow the test notification to flow through the existing notification code. This will provide a better user experience because before it was confusing when a test notification worked but the actual notification didn't, or vice versa.

### CODE REVIEW

**Comment by Emmo213** [comment]
It's been almost a month with no discussion. Should I close this PR as unwanted?

**Comment by Nachtzuster** [comment]
I haven't had much time these last months, so anything that looks non-trivial and/or not-a-bug-fix gets pushed back.

If you're still interested I can give some pointers on how to improve this PR

**Comment by Emmo213** [comment]
@Nachtzuster yes please. It's been working really well for me, but I'm open to suggestions as long as the end result is the same.

**Comment by Nachtzuster** [comment]
Rather that re-using `scripts/birdnet_analysis.py`, do it like `scripts/config.php` does it here: https://github.com/Nachtzuster/BirdNET-Pi/blob/3d99530ee5c2bbd7e942845b5cf6e10c111f81c6/scripts/config.php#L37

Also, as mentioned before, no changes to unrelated files, please

**Comment by Emmo213** [comment]
Your suggestion is to create a separate python file which invokes the existing notification logic?

**Comment by Nachtzuster** [comment]
correct

**Comment by Emmo213** [comment]
> correct

Moved the logic to its own file.

**Comment by Nachtzuster** [comment]
Interesting that you opted to wrap `apprise()` what is the reason you picked that one and not `sendAppriseNotifications()`

**Pull request closed without merging**
