### PR TITLE
Feature proposal : darkmode

### PR DESCRIPTION
**Pull request by alexbelgium**
- [x] create dark-style.css
- [x] modify views.php to take into account dark-styles.css instead of styles.css
- [x] create option in config.php and link with birdnet.conf (to align with how other options are managed)

Proposed style :

### CODE REVIEW

**Comment by alexbelgium** [comment]
Hi, still in draft but what do you think would you be interested?

it would be super simple : have a dark-style.css, a variable in birdnet.conf that says if light (default) or dark, and an icon to switch between both

**Comment by alexbelgium** [comment]
Just testing if people are interested - lots of testing still to do to check global site impact

**Comment by alexbelgium** [comment]
css should be as it is in an acceptable manner as long as people like the colors :-) of course we can adapt easily ; for example if people prefer a greener gray

**Comment by alexbelgium** [comment]
Mmh everything should work but I can't understand why my dark-style.css doesn't load (even if I duplicate style.css and just rename it)

**Comment by alexbelgium** [comment]
Ok, all should be good now

**Comment by Nachtzuster** [comment]
> Hi, still in draft but what do you think would you be interested?

I don't care much about dark themes _personally_, but I guess BirdNET-Pi users might :-)

I'll look into this later this week

**Comment by alexbelgium** [comment]
Thanks! Only not optimal place is the drop-down selection in options that are less readable, but i tried to avoid modifying the php pages. It would require to set a style I think specifically for those to correct their background

**Comment by Nachtzuster** [comment]
Code-wise this looks fine.
I'm guessing you're still finetuning for now, so let me know when you're done

**Comment by alexbelgium** [comment]
Thanks! I have solved the issues that I was raising above and will just have last look end of the week to be sure all is fine

**Comment by alexbelgium** [comment]
I guess it's good enough to merge! I don't see anything standing out and I've added an auto reload (same as for site name change) so that users directly see the impact of changing the color scheme!

**Comment by Nachtzuster** [comment]
... so I went to the dark side:
a couple things are still 'light themed' 
`tools->System Info`, `tools->File Manager` and `tools->Database Maintenance`

These are kinda expected, these are not trivial to convert, I guess.
The plan is to keep these as-is for now?

**Comment by alexbelgium** [comment]
Well I had a look but it would probably require changing the logic of how to pages (filebrowser and systeminfo) are called. Currently it seem a light theme is hard coded, so we might have to call them those with a specific argument from which they derive their color scheme. I can do that but it would a bit complexify the system

**Comment by Aixsponsa** [comment]
I was working on a better theme with dark mode support awhile ago but scrapped it. I'm not the best with Git but I would imagine it's somewhere in my long list of commits (I was doing a lot of testing at the time). It worked really well if I remember correctly. I just had to do a lot of changes to make everything look polished, which is when I stopped.

**Comment by alexbelgium** [comment]
Thanks ! I'll have a look. I didn't really want to recreate everything, just change the main css in a quick manner ;) I don't have that much time either to really develop a whole new theme... But we can start like that and move on to something more complex later !

**Comment by Nachtzuster** [comment]
> Well I had a look but it would probably require changing the logic of how to pages (filebrowser and systeminfo) are called. Currently it seem a light theme is hard coded, so we might have to call them those with a specific argument from which they derive their color scheme. I can do that but it would a bit complexify the system

I'm fine with merging your work as-is, just say the word

**Comment by alexbelgium** [comment]
Then let's go! And if I find a fast & easy solution for the third party tools (filebrowser and phpsysinfo) i'll make another pr - anyway it is not a core functionality

Thanks!

**Comment by bdeschut** [comment]
@alexbelgium It's silly, but wanted to let you know anyway. When using dark mode, the "X" to close the little detections over 30d graph is almost invisible:
image

**Comment by bdeschut** [comment]
@alexbelgium Same for the drop down menu's in tools > settings:
image

**Comment by alexbelgium** [comment]
Thanks, and background of weekly report and sort buttons in recordings. I'll try to have a look if it is from the main CSS

**Pull request merged**
