### PR TITLE
WIP : observation.org manual upload

### PR DESCRIPTION
**Pull request by alexbelgium**
Objective : allow upload of observations (+ linked sound) to observation.org (https://github.com/Nachtzuster/BirdNET-Pi/discussions/130)

New elements : 
- Files : 
    - "uploaded_observations_list.txt" (structure : uuid;site;filename)
    - upload_functions.php : functions to upload elements (can be used for more than observation.org subsites)
    - upload.svg : on click will upload the observation, only appears if an UPLOADSITE_SITE is defined
    - upload_ok.svg : show that the observation is uploaded, on click will lead you to the online observation
- Variables : "UPLOADSITE_SITE" ; "UPLOADSITE_USER" ; "UPLOADSITE_PASS"

Steps : 
- [x] config.php : 
    - [x] add observation.org credentials & token
    - [x] select observations site (observation.org / waarneming.nl / waarnemingen.be / observations.be)
    - [x] Sync all observations from the online site to the local database (for example in case of reinstall)
- [x] clear_all_data.sh : remove created file
- [x] install_services.sh : create file
- [x] install_config.sh : add new variables to birdnet.conf
- [x] update_birdnet_snippets.sh : add new variables to birdnet.conf
- [x] play.php : 
    - [x] if credentials provided in config.php, add button to call observation_upload.php
    - [x] if filename already uploaded to observation.org, provide link to url
    - [x] on click, upload observation and add to observations file
- [x] uploadsite.php
    - [x] create txt file to link observation.org uuid with filename
    - [x] authentification function (token retrieval)
    - [x] upload function

Out of scope : 
- Feat : daily automatic upload
- Feat : two way sync (update birdnet-pi based on observation.org update)
- UI : Visual page to summarize all uploaded elements with two way sync

Relevant documentation : 
- API detail : https://observation.org/api/v1/docs/observations.md
- Functional php implementation : https://github.com/Indicia-Team/drupal-8-modules-indicia_features/blob/master/recording_system_links/src/Plugin/RemoteRecordingSystemApi/ObservationOrg.php
- Implementation in powershell (only example found on github) : https://github.com/CigalesdeFrance/CARTES/blob/main/SCRIPTS/TELECHARGEMENTS.ps1

### CODE REVIEW

**Comment by lloydbayley** [comment]
Just to let you know, you have a mixture of observation.org and observations.org in the initial doc. Also, will this not ruffle feathers (PUN COMPLETELY INTENDED) since we are sending data to BirdWeather since the project started? Just wondering.

**Comment by Hiemstra87** [comment]
Should be Observation.org indeed. Thanks Lloydbayley!

**Comment by alexbelgium** [comment]
Thanks! Well birdweather.org and observation.org are both great tools with totally different purposes so I think both benefit from co-existence. Observation.org is really about posting individual, verified elements ; while birdweather is more about global stream of data and large scale observations

**Comment by lloydbayley** [comment]
Fair-enough. I've not used that one. I generally submit insects and spiders etc to iNaturalist.

**Comment by alexbelgium** [comment]
Needed from observation.org devs :
- client_ID : we should be issued one, can a single one be used
- species id and correspondance to scientific names

**Comment by lloydbayley** [comment]
Unsubscribe

**Comment by alexbelgium** [comment]
It is set in a generic manner to allow observation.org subsites, but also in the future potentially other sites such as inaturalist or ebird

**Comment by alexbelgium** [comment]
image

**Comment by alexbelgium** [comment]
Client if from observation.org required to proceed further : both sync observations uploaded and upload new observations. The PR will be reopened if there is progress on this side.

**Comment by ml-jeroen-28473838** [comment]
Any news on this thread @alexbelgium?

**Comment by alexbelgium** [comment]
Hi, observations.be did not seem interested and we can’t move forward without a client id. I’m moved on to other things to although it was at a pretty good state at that time

**Pull request closed without merging**
